import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import AnimatedText from '../components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '../components/Icons'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout>
          <div className='w-full'>
            <div className='font-bold mb-2 flex flex-col items-center self-center '>
              <AnimatedText text="Dhafin Raditya Juliawan" />
            </div>
            <div>
            <p>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
              Explore my latest projects and articles, showcasing my expertise in React.js and web development.
             </p>
            </div>
          </div>
          <div className='flex items-center self-start mt-5'>
            <Link href="\dummy" target={"_blank"} className='flex items-center bg-black text-light text-lg font-semibold p-2.5 px-4 rounded-xl
            hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
            transition duration-300'>
              Resume <LinkArrow className={"w-6 ml-1"}/>
              </Link>
            <Link href="mailto:dhafinraditya35@gmail.com" target={"_blank"} className='ml-6 text-lg font-medium capitalize underline '>Contact</Link>
          </div>
        </Layout>
      </main>
    </>
  )
}
